-- ============================================================
-- Post-deploy cron: nightly topic classification for the analytics dashboard
-- (pg_cron + pg_net)
--
-- WHY this is not a migration: like schedule-buffer-flush.sql, the job needs
-- your live prod URL and CRON_SECRET, which only exist AFTER the first Vercel
-- deploy. The extensions it relies on are enabled by migration
-- 20260615000003_enable_pg_cron_pg_net (applied via db push).
--
-- HOW to run: `node scripts/setup.mjs cron-apply` schedules it with the other
-- jobs (or `cron-sql` prints it filled in, to paste in the Supabase dashboard ->
-- SQL Editor). By hand: replace the two placeholders with the values from your
-- .env.local. It is idempotent: re-running updates the existing
-- 'classify-topics' job in place.
--
--   __APP_URL__      -> NEXT_PUBLIC_APP_URL  (e.g. https://your-app.vercel.app -- NO trailing slash)
--   __CRON_SECRET__  -> CRON_SECRET          (hex secret generated by scripts/setup.mjs)
--
-- TIMING. Every 5 minutes, all day. A conversation is picked an hour after
-- the customer's last message, so each run only has what settled since the
-- last one, and the dashboard (which shows up to yesterday) has yesterday
-- complete in every time zone. A run spends <= 100 s (maxDuration 120 s, under
-- the 180 s lease) and one with no work ends instantly. Classification has its
-- own daily token cap, so running during business hours takes nothing from the
-- bot's budget.
--
-- Night only instead: '*/5 4-8 * * *' (04:00-08:59 UTC). Two conversations of
-- the same customer get read together more often (about 15 % fewer calls in
-- the simulation), but a run reads 15-20 conversations, so the window holds
-- about 1,000 a night for the whole install, and what doesn't fit waits.
--
-- The interval (5 min) is LONGER than maxDuration, but that does NOT
-- guarantee exclusion: a net.http_get retry or a manual run overlaps two
-- requests. Exclusion comes from the leases in
-- select_conversations_to_classify and claim_topic_backfill (see
-- 20261002000001_classify_topics_rpcs).
-- ============================================================

select cron.schedule(
  'classify-topics',       -- unique job name; re-scheduling updates it in place
  '*/5 * * * *',
  $job$
    select net.http_get(
      url                  := '__APP_URL__/api/cron/classify-topics',
      headers              := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__'),
      timeout_milliseconds := 115000
    );
  $job$
);

-- Verify it registered (expect one active row):
--   select jobname, schedule, active from cron.job where jobname = 'classify-topics';
--
-- What the ROUTE answered (cron.job_run_details only confirms it was queued):
--   select id, status_code, content, created from net._http_response
--   order by created desc limit 10;
-- Expect 200 with {"ok":true,...}. 401 = CRON_SECRET mismatch; 500 = a phase failed.
--
-- Remove the job:
--   select cron.unschedule('classify-topics');
