-- ============================================================
-- Post-deploy cron: automation engine, every minute (pg_cron + pg_net)
--
-- WHY this is not a migration: the job needs your live prod URL and CRON_SECRET,
-- which only exist AFTER the first Vercel deploy. The extensions it relies on are
-- enabled by migration 20260615000003_enable_pg_cron_pg_net (applied via db push).
--
-- HOW to run: replace the two placeholders with the values from your .env.local,
-- then run this in the Supabase dashboard -> SQL Editor. (scripts/setup.mjs can
-- fill it for you and print the ready-to-paste SQL.) It is idempotent: re-running
-- updates the existing 'automations' job in place.
--
--   __APP_URL__      -> NEXT_PUBLIC_APP_URL  (e.g. https://your-app.vercel.app -- NO trailing slash)
--   __CRON_SECRET__  -> CRON_SECRET          (hex secret generated by scripts/setup.mjs)
--
-- Twin of schedule-buffer-flush.sql: same secret, same minute, different
-- endpoint. The two jobs are independent.
--
-- TIMING. The route budgets 50 s, strictly under this job's
-- one-minute interval; maxDuration = 60 EQUALS that interval, on purpose. In
-- normal operation ticks do not overlap; an accidental overlap is harmless
-- (FOR UPDATE SKIP LOCKED in the claim, UNIQUE (rule_id, event_id) in the
-- expansion) -- see route.ts for the full invariant. The explicit
-- timeout_milliseconds := 55000 replaces pg_net's 2 s default, which
-- would close Postgres' side of the request almost immediately. (Vercel does
-- NOT kill the function when pg_net hangs up -- schedule-buffer-flush.sql
-- relies on that -- so the risk this closes is not "the
-- route dies", it is overlapping ticks and blindness to a 500.)
-- ============================================================

select cron.schedule(
  'automations',           -- unique job name; re-scheduling updates it in place
  '* * * * *',             -- every minute
  $job$
    select net.http_get(
      url                  := '__APP_URL__/api/cron/automations',
      headers              := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__'),
      -- Under the 60 s interval: a request still in flight when the next tick
      -- fires is a bug, not a feature.
      timeout_milliseconds := 55000
    );
  $job$
);

-- Verify it registered (expect one active row):
--   select jobname, schedule, active from cron.job where jobname = 'automations';
--
-- Inspect the SCHEDULING of recent runs. Careful: pg_net is ASYNCHRONOUS, so a
-- 'succeeded' row here only means the net.http_get was QUEUED. It says nothing
-- about whether the route answered:
--   select status, return_message, start_time
--   from cron.job_run_details
--   where jobid = (select jobid from cron.job where jobname = 'automations')
--   order by start_time desc limit 10;
--
-- Inspect what the ROUTE actually answered -- this is the one that matters:
--   select id, status_code, content, created
--   from net._http_response
--   order by created desc limit 10;
-- Expect status_code = 200 and a content body with {"ok":true,...}. A 401 means
-- the CRON_SECRET in this job does not match the one deployed; a 500 or an
-- empty table means the route never answered.
--
-- Remove the job:
--   select cron.unschedule('automations');
