-- ============================================================
-- Post-deploy cron: nightly topic classification for the analytics dashboard
-- (pg_cron + pg_net)
--
-- WHY this is not a migration: like schedule-buffer-flush.sql, the job needs
-- your live prod URL and CRON_SECRET, which only exist AFTER the first Vercel
-- deploy. The extensions it relies on are enabled by migration
-- 20260615000003_enable_pg_cron_pg_net (applied via db push).
--
-- HOW to run: replace the two placeholders with the values from your
-- .env.local, then run this in the Supabase dashboard -> SQL Editor. It is
-- idempotent: re-running updates the existing 'classify-topics' job in place.
--
--   __APP_URL__      -> NEXT_PUBLIC_APP_URL  (e.g. https://your-app.vercel.app -- NO trailing slash)
--   __CRON_SECRET__  -> CRON_SECRET          (hex secret generated by scripts/setup.mjs)
--
-- TIMING. Every 5 minutes, only between 04:00 and 08:59 UTC (adjust the hour
-- range to your business' night). A run spends <= 50 s; the window repeats
-- runs until the backlog is empty, and a run with no work ends instantly. The
-- interval (5 min) is LONGER than maxDuration (60 s), but that does NOT
-- guarantee exclusion: a net.http_get retry or a manual run overlaps two
-- requests. Exclusion comes from the lease in
-- select_conversations_to_classify (see 20260915000001_classify_topics_rpcs).
-- ============================================================

select cron.schedule(
  'classify-topics',       -- unique job name; re-scheduling updates it in place
  '*/5 4-8 * * *',
  $job$
    select net.http_get(
      url                  := '__APP_URL__/api/cron/classify-topics',
      headers              := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__'),
      timeout_milliseconds := 55000
    );
  $job$
);

-- Verify it registered (expect one active row):
--   select jobname, schedule, active from cron.job where jobname = 'classify-topics';
--
-- What the ROUTE answered (cron.job_run_details only confirms it was queued):
--   select id, status_code, content, created from net._http_response
--   order by created desc limit 10;
-- Expect 200 with {"ok":true,...}. 401 = CRON_SECRET mismatch; 500 = a phase failed.
--
-- Remove the job:
--   select cron.unschedule('classify-topics');
